- name: gather network and hardware/vm facts
  setup:
    gather_subset: "!all,!min,hardware,network,virtual"

- name: define libvirt_kvm_guest
  set_fact:
    libvirt_kvm_guest: >-
      {{ ansible_virtualization_type == 'kvm'
          and ansible_virtualization_role == 'guest'
          and ansible_system_vendor == 'QEMU' }}

- import_tasks: configure-etc-hosts.yml
  tags: [configure-etc-hosts]

- import_tasks: configure-network-interfaces.yml
  tags: [configure_network_interfaces]

- import_tasks: configure-service-ip.yml
  tags: [configure_service_ip]

- import_tasks: configure-bgp.yml
  tags: [configure-bgp]

- import_tasks: configure-resolver.yml
  tags: [configure-resolver]

- import_tasks: configure-local-proxy.yml
  tags: [configure-local-proxy]

- import_tasks: configure-ubuntu-apt-sources.yml
  tags: [configure-ubuntu-apt-sources]

- import_tasks: configure-chrony.yml
  tags: [configure-chrony]

- import_tasks: configure-sshd.yml
  tags: [configure-sshd]

- import_tasks: configure-root-user-ssh.yml
  tags: [configure-root-user-ssh]
